### ISSUE TITLE
Cannot add extension with name 'crashlytics', as there is an extension already registered with that name.

### ISSUE THREAD

**Issue by therepo90** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#13]
## Steps to Reproduce the Problem

cordova build android
## Specifications

  - Plugin version:
  - Framework: latest
  - Framework version: latest
  - Operating system: windows
Using twitter-connect-login that contains plugin named 'crashlytics' as well
Error:
Cannot add extension with name 'crashlytics', as there is an extension already registered with that name.

**Comment by therepo90** [comment]
Its already implemented in google-firebase-plugin

**Comment by LiamKarlMitchell** [comment]
So how to fix it?

**Comment by Akankshaagrawal13** [comment]
how we can solve that error

**Comment by therepo90** [comment]
Just use only google-firebase-plugin or cordova-plugin-firebase-crashlytics :) That's it

**Comment by Mahesh1433** [comment]
how

**Comment by darrensapalo** [comment]
Your problem is that your plugins have conflicts with each other (two different plugins trying to initialize the same functionality which is crashlytics). Just use one plugin (that manages all the plugins that need to be applied), instead of trying to orchestrate all of it.

## How to use only one plugin

Assuming you wanted to use only the `google-firebase-plugin`:

1. Ensure your `package.json` uses the dependency `google-firebase-plugin` only. You do this by checking the `dependencies` property and the `devDependencies` property. You should not find any `cordova-plugin-firebase-crashlytics`. If you find any entries, delete that line.
2. Run `npm install` to make sure you have all the dependencies you need.
3. Run `cordova plugin remove cordova-plugin-firebase-crashlytics` to inform cordova you will not be using it anymore. This updates your `package.json` too. If this throws an error that you don't have that plugin, then that is good news- there's nothing to remove.
4. On your `plugins` folder, delete the folder named `cordova-plugin-firebase-crashlytics`. Otherwise, if that folder was still in your plugins folder, then it will be copied into your `platforms/android` project folder.
5. If you are sure you did not modify any of the generated files under the `platforms/` and `plugins/` folder, then you can also just `rm -rf platforms` and `rm -rf plugins` which deletes the whole platforms folder. After doing so, re-add your platforms using `cordova platform add android` and `cordova platform add ios` or whichever platforms you support. By re-adding your platforms, cordova will reproduce the `platforms/` and `plugins/` folder.

Personally, I recommend using the [Firebase X plugin](https://github.com/dpa99c/cordova-plugin-firebasex) instead of the `google-firebase-plugin`.
