### ISSUE TITLE
[Android] Crash on app launch

### ISSUE THREAD

**Issue by tominou** [ReallySmallSoftware/cordova-plugin-firebase-crashlytics#3]
cordova 8.0.0
cordova-android 7.1.0
android 7.1.2

The app crashes right when i open it after installing the plugin. Building process seems fine.

Here is the error:
> java.lang.RuntimeException: Unable to get provider com.crashlytics.android.CrashlyticsInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.crashlytics.android.CrashlyticsInitProvider" on path: DexPathList[[zip file "/data/app/com.myapp-1/base.apk"],nativeLibraryDirectories=[/data/app/com.myapp-1/lib/arm64, /system/lib64, /vendor/lib64]]

Thank you

**Comment by ReallySmallSoftware** [comment]
What version of Android is this on? Is it 5?

On 7 Mar 2018 19:20, "tominou" <notifications@github.com> wrote:

The app crashes right when i open it after installing the plugin. Building
process seems fine.

Here is the error:

java.lang.RuntimeException: Unable to get provider
com.crashlytics.android.CrashlyticsInitProvider:
java.lang.ClassNotFoundException: Didn't find class
"com.crashlytics.android.CrashlyticsInitProvider" on path: DexPathList[[zip
file "/data/app/com.tennistemple-1/base.apk"],nativeLibraryDirectories=[/
data/app/com.tennistemple-1/lib/arm64, /system/lib64, /vendor/lib64]]

Thank you

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ReallySmallSoftware/cordova-plugin-firebase-crashlytics/issues/3>,
or mute the thread

**Comment by tominou** [comment]
Sorry for the missing info, i use:
cordova 8.0.0
cordova-android 7.1.0
android 7.1.2

**Comment by tominou** [comment]
The issue was from `cordova-support-google-services` which uses `com.google.gms:google-services` version `3.1.0` while firebase crashlytics requires `3.1.2` or higher.

Change `3.1.0` to `3.1.2` in the file `platforms/android/cordova-support-google-services/{name of your app}-build.gradle` to fix that issue.

Thank you

**Comment by ReallySmallSoftware** [comment]
Thank you for letting me know how you fixed this issue.
